title: Håndbog til OS2-fællesskabet
description: Praktiske rutiner, værktøjer og principper i OS2 og sekretariatet.
logo: "/assets/images/os2_logo.png"

# --- Tema / build ---
theme: just-the-docs 

# --- Integrations ---
mermaid:
  version: "11.9.0"

aux_links:
  Repository: https://github.com/zorp/os2-sekretariat-docs
  Maintainers: ./MAINTAINERS
  Contribute: ./CONTRIBUTING

# UI-komponenter (Just the Docs)
callouts_level: quiet
callouts_opacity: 0.2

callouts:
  cta:          # så kan du skrive "{: .cta}" i Markdown
    color: os2green
